#!/bin/sh /etc/rc.common

START=90
STOP=15
USE_PROCD=1
#PROCD_DEBUG=1

NAME=minivtun
BINARY=/usr/sbin/minivtun

_log() {
	logger -p "daemon.$1" -t "$NAME" "$2"
}

has_valid_server() {
	local server
	for server in $@; do
		[ "$(uci_get $NAME $server)" = "servers" ] && return 0
	done
	return 1
}

validate_config_section() {
	uci_validate_section "$NAME" general "$1" \
		'server:uciname' \
		'daemon_user:string:root'
}

validate_server_section() {
	uci_validate_section "$NAME" servers "$1" \
		'server_addr:host' \
		'server_port:port:1414' \
		'password:string' \
		'local_family:or("IPv4", "IPv6"):IPv4' \
		'mtu:range(296,1500)' \
		'other_args:string' \
		'local_ipaddr4:string' \
		'local_ipaddr6:string' \
		'cipher_mode:string'
}

start_instance() {
	local server="$1"

	if [ -z "$server" -o "$server" == "nil" ]; then
		return 0
	elif ! validate_server_section "$server"; then
		_log "err" "Server config validation failed."
		return 1
	fi
	
	local daemon_file args
	daemon_file="/var/run/${NAME}.${server}.pid"
	
	args="-r [$server_addr]:$server_port -e $password -m $mtu -t $cipher_mode $other_args"
	
	if [ "IPv4" = "$local_family" ]; then
		args="$args -a $local_ipaddr4"
	else
		args="$args -A $local_ipaddr6"
	fi
	
	procd_open_instance
	procd_set_param command $BINARY
	procd_append_param command $args
	[ -n "$daemon_user" ] && procd_set_param user "$daemon_user" && _log "info" "running from ${daemon_user} user"
	procd_set_param pidfile "$daemon_file"
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
}

start_service() {
	if ! validate_config_section "general" ; then
		_log "err" "Config validate failed."
		return 1
	fi
	has_valid_server $server || return 1
	
	for srv in $server; do
		start_instance $srv
	done
}
